------------------------------------------------
------------  GERSON VARGAS DBA-----------------
------------------------------------------------
drop DATABASE INTRANET_BD;
CREATE DATABASE INTRANET_BD;
USE INTRANET_BD;
CREATE TABLE IF NOT EXISTS USUARIOS (
   EMAIL VARCHAR(100),
   USERNAME VARCHAR(20),
   TIPO INT DEFAULT 1,
   IMAGEN VARCHAR(100),
   PASSWORD BLOB,
   PRIMARY KEY(EMAIL)
) ENGINE = INNODB ROW_FORMAT = DEFAULT;

CREATE TABLE IF NOT EXISTS  EMPLEADOS (
	ID VARCHAR(20), 
	NOMBRE_COMPLE VARCHAR(200), 
	DEPARTAMENTO VARCHAR(100), 
	UNIDAD VARCHAR(100), 
	PUESTO VARCHAR(100),
	PRIMARY KEY(ID)	
	) ENGINE = INNODB ROW_FORMAT = DEFAULT;	
	
CREATE TABLE IF NOT EXISTS  CONTACTOS (
	ID_EMPLEADO VARCHAR(20), 
	CORREO VARCHAR(60), 
	TELEFONO VARCHAR(20), 
	CELULAR VARCHAR(20),
	PRIMARY KEY(ID_EMPLEADO,CORREO),
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID) ON UPDATE CASCADE ON DELETE RESTRICT
	) ENGINE = INNODB ROW_FORMAT = DEFAULT;